
spring:
    profiles:
        active: development
        
    # spring datasource jpa
    datasource: 
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./database/crud_rest_api
        username: root
        password: root
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
    
    # spring hibernate    
    jpa: 
        generate-ddl: true
        show-sql: true
        properties: 
            hibernate: 
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

    # jackson config
    jackson: 
        serialization: 
            indent_output: true
            
# tomcat konfiguration
server: 
    port : 9000
    tomcat: 
        access_log_enabled: true
        basedir: target/tomcat
    
